# Generated by Django 3.2.13 on 2022-06-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220620_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='model',
            new_name='name',
        ),
    ]
