# Generated by Django 3.2.13 on 2022-06-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_model_topic_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-update', 'created']},
        ),
    ]
